### ISSUE TITLE
requests and six dependencies not working in pip

### ISSUE THREAD

**Issue by bbirand** [inboxapp/inbox-python#3]
I was just trying to install inbox using pip in a virtualenv. First time I ran `pip install inbox`, there was an error saying that `requests` could not be found. After I installed requests, it said the same about `six`. After that, pip install worked fine. Just an FYI.

**Comment by jennielees** [comment]
Thanks, this was due to over-zealous imports in `setup.py`: fixed in 0186ad3027b86c64c0829d17b73e6a743d13480e.
